<a href="https://colab.research.google.com/github/Paulokw/User-User-Recommendation-System/blob/main/User_User_Movie_Recommendation_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install fuzzywuzzy
import pandas as pd
import numpy as np
from fuzzywuzzy import fuzz
from fuzzywuzzy import process

Requirement already satisfied: fuzzywuzzy in /usr/local/lib/python3.12/dist-packages (0.18.0)

In [ ]:
ratings=pd.read_csv('ratings.csv')
movies=pd.read_csv('movies.csv')

In [ ]:
ratings.head()

   userId  movieId  rating     timestamp
0       1    296.0     5.0  1.147880e+09
1       1    306.0     3.5  1.147869e+09
2       1    307.0     5.0  1.147869e+09
3       1    665.0     5.0  1.147879e+09
4       1    899.0     3.5  1.147869e+09

In [ ]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [ ]:
final_df=ratings.pivot(index='userId',columns='movieId',values='rating')

In [ ]:
final_df.head()

movieId,NaN,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,...,207309.0,207367.0,207405.0,207642.0,207890.0,208002.0,208080.0,208737.0,208793.0,208939.0
userId,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,3.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
final_df.fillna(0,inplace=True)

In [ ]:
from scipy.sparse import csr_matrix

In [ ]:
mat_users=csr_matrix(final_df.values)

In [ ]:
from sklearn.neighbors import NearestNeighbors

In [ ]:
knn=NearestNeighbors(metric='cosine',algorithm='brute',n_neighbors=20)

In [ ]:
knn.fit(mat_users)

NearestNeighbors(algorithm='brute', metric='cosine', n_neighbors=20)

In [ ]:
def recommend(movie_name,data,model,n_recommendations):
  model.fit(data)
  idx=process.extractOne(movie_name,movies['title'])[2]
  print('Movie Selected: ',movies['title'][idx],'Index: ',idx)
  print('Searching for recommendations.....')
  distances,indices=model.kneighbors(data[idx],n_neighbors=n_recommendations)
  for i in indices:
    print(movies['title'][i].where(i!=idx))

In [ ]:
recommend('Jumanji',mat_users,knn,20)

Movie Selected:  Jumanji (1995) Index:  1
Searching for recommendations.....
1                                                     NaN
4058                                  See Spot Run (2001)
1019                            That Thing You Do! (1996)
1207                               Terminator, The (1984)
185                                     Party Girl (1995)
3553    City of the Living Dead (a.k.a. Gates of Hell,...
3111                         Boys from Brazil, The (1978)
1943                       Barefoot Executive, The (1971)
2160                   Cabinet of Dr. Ramirez, The (1991)
2810                                     Psycho II (1983)
3823               Voyage to the Bottom of the Sea (1961)
1974            Seventh Heaven (Septième ciel, Le) (1997)
2499                                 Hideous Kinky (1998)
3009                                   Jagged Edge (1985)
856                                Nothing to Lose (1994)
2516                                      Get Real (1998)
3537    Those Who Love Me Can Take the Train (Ceux qui...
461                           Hot Shots! Part Deux (1993)
2378                         Peggy Sue Got Married (1986)
580                                        Aladdin (1992)
Name: title, dtype: object